Repository hiromon0125/ritchie-bus-schedule, pull requests merged in 2025-03, with the labels that each got.

#79 Feat posthog analytics
  .env.example
  package.json
  pnpm-lock.yaml
  src/app/_components/posthog.tsx
  src/app/_components/share.tsx
  src/app/about/page.tsx
  src/app/bus/[busId]/page.tsx
  src/app/layout.tsx
  src/env.js
  src/server/api/trpc.ts
Labels: enhancement

#94 Feat/theme revamp
  .env.example
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  postcss.config.cjs
  src/app/_components/DotMap.tsx
  src/app/_components/Map.tsx
  src/app/_components/RouteMapOr.tsx
  src/app/_components/animatedList.tsx
  src/app/_components/busStatus.tsx
  src/app/_components/busStatusString.tsx
  src/app/_components/editors/editBusDetail.tsx
  src/app/_components/favBtn.tsx
  src/app/_components/footer.tsx
  src/app/_components/header.tsx
  src/app/_components/posthog.tsx
  src/app/_components/profileBtn.tsx
  src/app/_components/serviceinfo.tsx
  src/app/_components/tags.tsx
  src/app/_components/timeTable.tsx
  src/app/_components/userButton.tsx
  src/app/_components/welcome.tsx
  src/app/about/page.tsx
  src/app/bus/[busId]/@map/layout.tsx
  src/app/bus/[busId]/@timetable/default.tsx
  src/app/bus/[busId]/@timetable/loading.tsx
  src/app/bus/[busId]/@timetable/page.tsx
  src/app/bus/[busId]/layout.tsx
  src/app/bus/[busId]/loading.tsx
  src/app/bus/[busId]/page.tsx
  src/app/buses/layout.tsx
  src/app/buses/loading.tsx
  src/app/buses/page.tsx
  src/app/layout.tsx
  src/app/manage/bus/[busId]/page.tsx
  src/app/manage/page.tsx
  src/app/manage/stop/[stopId]/page.tsx
  src/app/page.tsx
  src/app/pp/page.tsx
  src/app/setting/page.tsx
  src/app/stop/[stopId]/layout.tsx
  src/app/stop/[stopId]/page.tsx
  src/app/stops/layout.tsx
  src/app/stops/loading.tsx
  src/app/stops/page.tsx
  src/app/user-profile/[[...user-profile]]/page.tsx
  src/components/ui/button.tsx
  src/components/ui/dialog.tsx
  src/components/ui/popover.tsx
  src/components/ui/switch.tsx
  src/components/ui/toast.tsx
  src/server/api/routers/bus.ts
  src/server/api/routers/favorite.ts
  src/server/api/routers/routes.ts
  src/server/api/routers/stops.ts
  src/server/api/trpc.ts
  src/styles/bus.module.css
  src/styles/globals.css
  tailwind.config.ts
  vercel.json
Labels: bug, enhancement, dependencies

#89 Swap out rating form for Urbanism Club's Rate my Ride form
  src/app/_components/userButton.tsx
  src/app/bus/[busId]/layout.tsx
  src/app/stop/[stopId]/layout.tsx
  src/app/stop/[stopId]/page.tsx
Labels: good first issue
